In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,4,6,4])
print(arr)
x=np.where(arr==4)
print(x)

[1 2 3 4 5 4 6 4]
(array([3, 5, 7]),)


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(arr)
print(x)

[1 2 3 4 5 6 7 8]
(array([1, 3, 5, 7]),)


In [ ]:
#sorting the array
import numpy as np
arr=np.array([3,2,0,1])
print("\nOriginal array:",arr)
print("\nSorted array:",np.sort(arr))
arr=np.array([[3,2,4],[5,0,1]])
print("\nOriginal array",arr)
print("\nSorted array",np.sort(arr))


Original array: [3 2 0 1]

Sorted array: [0 1 2 3]

Original array [[3 2 4]
 [5 0 1]]

Sorted array [[2 3 4]
 [0 1 5]]


In [2]:
#filter
import numpy as np
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print("\nOriginal array",arr)
print("\nFilter index:",x)
print("\nFilter array",newarr)



Original array [41 42 43 44]

Filter index: [True, False, True, False]

Filter array [41 43]


In [6]:
import numpy as np
arr=np.array([41,42,43,44])
Filter_arr=arr>42
newarr=arr[Filter_arr]
print("\n Original array:",arr)
print("\n Filter array:Codition->42:",Filter_arr)
print("\n New array:",newarr)


 Original array: [41 42 43 44]

 Filter array:Codition->42: [False False  True  True]

 New array: [43 44]
